### ISSUE TITLE
Events -> Leakages: how are leaks modeled in epyt-flow? I see leaks are assigned to pipes, unlike in EPANET,  where leaks are modeled by assigning emitter coefficients to junctions.

### ISSUE THREAD

**Issue by andreArtelt** [WaterFutures/EPyT-Flow#13]

**Comment by andreArtelt** [comment]
I extended the documentation of leakages and included a more detailed description.

Leakages are modeled by emitter coefficients. Leaks can be placed at nodes or pipes -- in the latter case, the pipe is split into two parts connected by a new node at which the leak is placed.

**Comment by meghnathomas** [comment]
Great, thanks!
