### ISSUE TITLE
Events -> Actuator events: actuator events are analogous to EPANET time-based controls, correct? What takes precedence if you have both an actuator event and a control acting on an element (e.g., a pump)?

### ISSUE THREAD

**Issue by andreArtelt** [WaterFutures/EPyT-Flow#15]

**Comment by andreArtelt** [comment]
Control rules such as time-based rules specified in the .inp file will be prioritized.
Other than that, EPyT-Flow first applies events and then controls -- i.e. events are always prioritized over controls.

**Comment by meghnathomas** [comment]
Great, thanks!
