### ISSUE TITLE
What is the default sensor placement for each network/scenario?

### ISSUE THREAD

**Issue by andreArtelt** [WaterFutures/EPyT-Flow#16]

**Comment by andreArtelt** [comment]
The default, when loading an .inp file and specifying anything else, is an empty sensor config -- i.e. no sensors anywhere. However, some networks and scenarios included in EPyT-Flow do come with a default sensor placement.

I added a brief statement to the documentation.

**Comment by meghnathomas** [comment]
Thank you! Can you point me to where in the docs I could find the networks and scenarios that do have a default sensor placement?

**Comment by andreArtelt** [comment]
A list of all included networks is given in https://epyt-flow.readthedocs.io/en/stable/tut.scenarios.html#predefined-networks -- from those, Hanoi and L-Town come with a default sensor placement.
