### ISSUE TITLE
Events -> Sensor faults: currently epyt-flow can model only one kind of fault affecting any sensor, right? Just curious - in the future, will you consider allowing multiple faults to affect sensors?

### ISSUE THREAD

**Issue by andreArtelt** [WaterFutures/EPyT-Flow#21]

**Comment by andreArtelt** [comment]
> Events -> Sensor faults: currently epyt-flow can model only one kind of fault affecting any sensor, right? Just curious - in the future, will you consider allowing multiple faults to affect sensors?

It is already possible to have multiple sensor faults acting on the same sensor -- having different faults for different sensors is also possible. This is also stated in the documentation on events -- in the very end when describing sensor reading events. However, to clarify this, I just added another remark to the sensor fault subsection.

**Comment by meghnathomas** [comment]
Perfect, thank you!
