### ISSUE TITLE
A suggestion: I think it would be nice to add a page at the beginning of the in-depth tutorial summarizing the functionalities epyt-flow offers.  This could include a complete list of the uncertainties, events, faults, and controls you allow users to model, and ideally would include time series or spatial plots to better visualize these things (e.g., abrupt and incipient leaks, sensor override attacks, different uncertainty distributions, etc). Having all of these cases in one single page could provide users with a clear overview of what the package offers

### ISSUE THREAD

**Issue by andreArtelt** [WaterFutures/EPyT-Flow#22]

**Comment by andreArtelt** [comment]
This is a great idea, but it is not clear to me how to best implement it. Because EPyT-Flow offers so much functionalities, it is easy to overwhelm the user.
After some time, I decided to create a somewhat detailed list of features and functionalities and put it as a "table of contents" in front of the in-depth tutorial -- by this, the user not only gets an overview of the functionalities and features but also gets help in navigating the extensive in-depth tutorial (hopefully it helps the user to quickly find what their are looking for).

I attached a screenshot of the new page, so you can have a look without compiling the documentation. Let me know what you think.
![Screenshot_2024-10-16_07-42-36](https://github.com/user-attachments/assets/3d508ecd-9459-4319-abd6-f9de8e52616b)

**Comment by meghnathomas** [comment]
@andreArtelt thanks, I think this is great! It is very clear to see what EpyT-Flow allows users to do.
