### ISSUE TITLE
geodataframes objects

### ISSUE THREAD

**Issue by jorgelcq** [WaterFutures/EPyT-Flow#8]
hello, with respect to the graph could you use shapely objects and geodataframe to get a preview, how to modify node locations, sure you know, but I would do it if I could. Thank you by the way I really liked what you did. 

with geopandas:

```Python
gdf.explore()
```

![image](https://github.com/WaterFutures/EPyT-Flow/assets/121756835/3d22c51a-3602-4b6e-957b-c9ceed16eb87)

with leafmap:

```Python
Map = leafmap.Map()

Map.add_basemap("HYBRID")

Map.add_gdf(gdf, style = {"color": "red"}, layer_name = "layer")

Map
```

![image](https://github.com/WaterFutures/EPyT-Flow/assets/121756835/d511a4d1-4d25-41c5-a386-0a809c1057d9)

```Python
gdf
```

![image](https://github.com/WaterFutures/EPyT-Flow/assets/121756835/0cfce8eb-b6a6-482e-8df8-0b599e9e4dde)

Although it would be better with folium, which has many icons and several configurations to make the previews of points, but it is a little longer to make them.

**Comment by andreArtelt** [comment]
Hi, thanks for bringing this up.
Since you closed this issue, I assume that you solved your problem? Nevertheless, I want to let you know that I just added the node coordinates to the `NetworkTopology` class -- the changes will be included in the next release.

Let me know if there are any other issues.

**Comment by jorgelcq** [comment]
Hi, it actually works well, I should have checked the documentation more. Although I did manage to see it in a geodataframe, but maybe including that for something so specific is not very profitable.

Thank you all the same for the effort you put in.

✋🏼 Greetings from Peru.

**Comment by andreArtelt** [comment]
That's great :)

However, I think other people might be interested in smth. similar. So I decided to add a function `to_gis()` to export a NetworkTopology instance to `geopandas.GeoDataFrame` instances -- available on the dev branch (will be part of the next release)

A minimal working example:
```Python
# Load .inp file
with ScenarioSimulator(f_inp_in="Net1.inp") as wdn:
    # Get topology
    topo = wdn.get_topology()

    # Get topology as GeoDataFrame instances
    geo_data = topo.to_gis()

    # Show GeoDataFrame for nodes
    print(geo_data["nodes"].head())
```
