### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by meghnathomas** [WaterFutures/EPyT-Flow#9]
Hi! I will be conducting my JOSS review in this issue.

epyt-flow is a really interesting and useful package that offers a large range of functions and very comprehensive documentation! The inclusion of several benchmark networks and scenarios from the literature is a great touch and will aid in adoption by water distribution systems (WDS) researchers. I was able to successfully install the package (using pip) and run all examples. Below I have included comments and questions on different aspects of the package, repository, and docs. 

General

- [x] It was a little unclear to me how SCADA data is generated. Is SCADA data basically = pressure/flow simulations results for the nodes/links at which sensors are installed? So if we run a simulation with no uncertainties and no events, will SCADA data results be equal to the results of a basic hydraulic simulation as performed by EpyT or WNTR? 
- [ ] If I have a network model of a real WDS + SCADA data collected from meters placed throughout the system, I see from Docs -> In-depth Tutorial -> SCADA data that I can use epyt-flow to analyze the model and integrate the data. Would you be able to add an example demonstrating this (perhaps using a common network such as C-TOWN or BWFLNet)?
- [x] Can epyt-flow read controls from the .INP file of a model or must a user define an AdvancedControlModule class to specify controls (like those shown in the Custom Controls example)?
- [x] #16

Landing page

- [x] I recommend adding a line of code to plot a timeseries of the pressure and flow SCADA data results + the actual plots themselves for the Quick Example
- [x] #14

Docs: in-depth tutorial

- [x] #22
- [x] #12
- [x] #11
- [x] #20
- [x] Control: I see that in the example you set the tank diameter by calling `self.__tank_diameter = 50.5`. Is it possible to change all system parameters (e.g., pipe diameter, node elevation) in this way? 
- [x] Control: EPANET offers simple time based controls, simple event based controls, and rule based controls. Can we use epyt-flow to model rule-based controls as well?
- [x] #13
- [x] #15
- [x] #21

Docs: examples

- [x] #18
- [x] Working with Network Topology: when we list the edges with `print(topo.edges)`, why is the second element in each tuple a string?
- [x] Uncertainties Example: I am a huge fan of epyt-flow's ability to add uncertainties to model parameters! What parameters can one add uncertainty to besides demand patterns? And can we add different kinds of uncertainty to, say, different demand patterns or base demands or must all instances of a parameter be assigned the same uncertainty?
- [x] #19
- [x] Water Age Analysis and Chloring Injection: would the results for these two examples be the same as in EPANET?
- [x] #17

Examples 
- [x] I recommend adding the plotting functions from the docs into the Python files so users can immediately generate and reproduce your plots and do not have to refer to the docs (like for the event detection and net2-cl2 examples)

Paper

- [x] You mention that WNTR does not consider industrial controls, but I believe it offers the same control functionalities that epyt-flow does (simple event- and time-based controls) as well as control rules!

**Comment by andreArtelt** [comment]
Thanks a lot for this detailed and constructive feedback - much appreciated 🙏

I am currently on vacation until 5th October - I will work on those aspects once I am back in office.
Thanks for your understanding.

Best,
André

**Comment by andreArtelt** [comment]
I was busy with administrative tasks the last days after I returned from a longer vacation -- sorry about the delay.

Regarding your comment on the paper: I think I did not make this clear enough in the paper. EPyT-Flow supports arbitrary controls that go beyond "simple" IF-THEN-ELSE rules as supported by EPANET. For instance, you could use a neural network to make control decisions based on the observed sensor readings. I added a clarifying statement to the paper and documentation in commit dee0de5
Let me know, what you think.

Also, how do you want me to work on your comments/tasks. There are quite a few of them and I was wondering whether it would make sense to convert some of them into issues to have a better overview.

**Comment by meghnathomas** [comment]
Hi @andreArtelt  sorry for the late reply! That works for me - would you like me to split this comment up into separate issues or would you prefer to do that yourself?

**Comment by andreArtelt** [comment]
> Hi @andreArtelt sorry for the late reply! That works for me - would you like me to split this comment up into separate issues or would you prefer to do that yourself?

I can do that myself. I think I might just reply to some of your comments in this issue if your comment is more a question than an issue that requires changes (i.e. commits).

**Comment by andreArtelt** [comment]
> I recommend adding a line of code to plot a timeseries of the pressure and flow SCADA data results + the actual plots themselves for the Quick Example

Was already addressed in [9f2c895](https://github.com/WaterFutures/EPyT-Flow/commit/9f2c8951487a433d439b1da9b2803cec1f75e92b)

**Comment by andreArtelt** [comment]
> You mention that WNTR does not consider industrial controls, but I believe it offers the same control functionalities that epyt-flow does (simple event- and time-based controls) as well as control rules!

Was addressed in one of my previous comments and in [dee0de5](https://github.com/WaterFutures/EPyT-Flow/commit/dee0de592b8f3eb1fcf82eadc054d198e44ca398)

**Comment by andreArtelt** [comment]
> Water Age Analysis and Chloring Injection: would the results for these two examples be the same as in EPANET?

Yes, the results would be exactly the same because EPyT-Flow uses EPANET for the simulation.

**Comment by andreArtelt** [comment]
> Can epyt-flow read controls from the .INP file of a model or must a user define an AdvancedControlModule class to specify controls (like those shown in the Custom Controls example)?

Right now,  controls from .INP files are not parsed. I think, this smth. for a future release.

**Comment by andreArtelt** [comment]
> Working with Network Topology: when we list the edges with print(topo.edges), why is the second element in each tuple a string?

Every element in each tuple should be a string -- if you observe any other behavior, please create a bug report.

The result of `topo.edges` is a list of tuples (edges) -- each edge is represented by the IDs (strings) of the two nodes which it is connecting.

**Comment by meghnathomas** [comment]
> > Working with Network Topology: when we list the edges with print(topo.edges), why is the second element in each tuple a string?
> 
> Every element in each tuple should be a string -- if you observe any other behavior, please create a bug report.
> 
> The result of `topo.edges` is a list of tuples (edges) -- each edge is represented by the IDs (strings) of the two nodes which it is connecting.

Ok I see - I think I was confused because in your [docs ](https://epyt-flow.readthedocs.io/en/stable/examples/network_topology.html)(code block 7), it looks like the first element of the tuple is a regular string while the second element is a numpy.string_. Not a big deal!

**Comment by andreArtelt** [comment]
> > > Working with Network Topology: when we list the edges with print(topo.edges), why is the second element in each tuple a string?
> > 
> > 
> > Every element in each tuple should be a string -- if you observe any other behavior, please create a bug report.
> > The result of `topo.edges` is a list of tuples (edges) -- each edge is represented by the IDs (strings) of the two nodes which it is connecting.
> 
> Ok I see - I think I was confused because in your [docs ](https://epyt-flow.readthedocs.io/en/stable/examples/network_topology.html)(code block 7), it looks like the first element of the tuple is a regular string while the second element is a numpy.string_. Not a big deal!

Oh, I never checked the readthedocs version since it looks fine on my local machine (i.e. no numpy.string_) -- I will investigate this.

**Comment by andreArtelt** [comment]
> Control: I see that in the example you set the tank diameter by calling self.__tank_diameter = 50.5. Is it possible to change all system parameters (e.g., pipe diameter, node elevation) in this way?

This does not change any EPANET parameters. This is just a local variable that is used in the control rule. As mentioned in the comment (in the notebook), the value could have been obtained by calling an EPANET function as well. However, changing this local variable has no effect on the actual tank diameter. The tank diameter can be changed by either editing the .inp file or by calling EPyT functions such as `setNodeTankDiameter`

**Comment by andreArtelt** [comment]
> Uncertainties Example: I am a huge fan of epyt-flow's ability to add uncertainties to model parameters! What parameters can one add uncertainty to besides demand patterns? And can we add different kinds of uncertainty to, say, different demand patterns or base demands or must all instances of a parameter be assigned the same uncertainty?

Uncertainties can be added to all parameters which are listed in the documentation of the `ModelUncertainty` class (see https://epyt-flow.readthedocs.io/en/stable/epyt_flow.uncertainty.html#epyt_flow.uncertainty.model_uncertainty.ModelUncertainty)

Right now, only "global" uncertainties can be added -- e.g. one type of uncertainty for all base demands. Being able to be more selective (e.g. having different kinds of uncertainties for different base demands) is a great idea and will be added to my todo list for future releases of EPyT-Flow :)

**Comment by andreArtelt** [comment]
> It was a little unclear to me how SCADA data is generated. Is SCADA data basically = pressure/flow simulations results for the nodes/links at which sensors are installed? So if we run a simulation with no uncertainties and no events, will SCADA data results be equal to the results of a basic hydraulic simulation as performed by EpyT or WNTR?

Yes, SCADA data refers to the simulation results (pressure, flows, species concentrations, pump states, etc.) that are accessible to the user by placing sensors. However, those SCADA data (i.e. sensor readings) might be affected by sensor faults, uncertainties, etc. Without any uncertainties and sensor faults, the results are the same as in EPyT/EPANET and should not differ much from WNTR (be aware of the units!).

**Comment by andreArtelt** [comment]
> If I have a network model of a real WDS + SCADA data collected from meters placed throughout the system, I see from Docs -> In-depth Tutorial -> SCADA data that I can use epyt-flow to analyze the model and integrate the data. Would you be able to add an example demonstrating this (perhaps using a common network such as C-TOWN or BWFLNet)?

I am not sure if I understand you correctly. Do you want to load real SCADA data into EPyT-Flow? If so, this could be done by manually creating an instance of `ScadaData` (see https://epyt-flow.readthedocs.io/en/stable/epyt_flow.simulation.scada.html#epyt_flow.simulation.scada.scada_data.ScadaData) -- however, I am not sure what you want to analyze or integrate in this context.

**Comment by meghnathomas** [comment]
> > If I have a network model of a real WDS + SCADA data collected from meters placed throughout the system, I see from Docs -> In-depth Tutorial -> SCADA data that I can use epyt-flow to analyze the model and integrate the data. Would you be able to add an example demonstrating this (perhaps using a common network such as C-TOWN or BWFLNet)?
> 
> I am not sure if I understand you correctly. Do you want to load real SCADA data into EPyT-Flow? If so, this could be done by manually creating an instance of `ScadaData` (see https://epyt-flow.readthedocs.io/en/stable/epyt_flow.simulation.scada.html#epyt_flow.simulation.scada.scada_data.ScadaData) -- however, I am not sure what you want to analyze or integrate in this context.

This feature would be very useful in calibration and state estimation tasks where we want to use information from both the hydraulic simulation results and sparse SCADA data to correct parameters (like pipe roughnesses) or estimate real-time system-wide pressures and flows. There are different methods to actually perform the state estimation/calibration procedures, and I am not concerned about the implementation of those - just wondering how one could use EpyT-Flow to access a hydraulic model of their own network and use the function in the link you provided to bring in SCADA data! Does that make sense?

I'm asking this because I have been trying to test a simple example to see how EpyT-Flow could be used to load a custom network that is not built into your collection of networks/scenarios. I am trying this out with CTown (I know CTown is in your database but I am trying to load the network as an INP file and load in [sensor data](http://www.water-simulation.com/wsp/about/bwcn/) using numpy arrays). At this point I am not concerned with the analysis, I am just pretending I am a user trying to load my own network and data so I can do my own analyses later. Can you walk me through that procedure?  E.g., to manually create an instance of ScadaData, it looks like I have to build a new sensor config. When I build a new [sensor config](https://epyt-flow.readthedocs.io/en/stable/epyt_flow.simulation.html#epyt_flow.simulation.sensor_config.SensorConfig), how can I access the list of nodes and links etc from the network INP file? It is a little challenging to navigate the EpyT-Flow code to work with networks/data that are not loaded into the package, so any guidance would be appreciated! And please let me know if this question or comment doesn't make sense I am happy to elaborate further

**Comment by andreArtelt** [comment]
Okay, I think I understood what you wanted to do. This is an interesting application of EPyT-Flow that I have not considered before. So far, I have always used (and built) EPyT-Flow to generate data but not to load external data (this is why there are export mechanisms for SCADA data but not import mechanisms).

Regarding your use case, here is how I would do it (I have not tested this -- there might be some typos xD):

```python
# Load .inp file
ScenarioSimulator(f_inp_in="CTown.inp") as scenario:
	  # 1. Build a sensor placement that is consistent with the data that you want to load and analyze
          # You could also do this after running the simulation if you whish to have different sensor configurations for the external data and the simulated data 
	  scenario.set_pressure_sensors(sensor_locations=[...])
	  sim.set_flow_sensors(sensor_locations=[...])
	  # ...
	  
	  # 2. Export this sensor config
	  my_sensor_config = sim.sensor_config()
	  
          # 3. Run simulation
          scada_data = scenario.run_simulation()

	  # 4. Load external SCADA data -- everything must be a Numpy array!
	  my_measurement_time_points = ...
	  my_pressure_data = ...
	  my_flow_data = ...
	  # ...
	  
	  # 5. Create a SCADA data instance containing the external
	  my_scada_data = ScadaData(sensor_config=my_sensor_config,
			            frozen_sensor_config=True,	# Assuming that the sensor config can not be changed -- set this to False if you loaded data for every node and link in the network!
                                    sensor_readings_time=my_measurement_time_points,
                                    pressure_data_raw=my_pressure_data
                                    flow_data_raw=my_flow_data
                                    ...)
	  
	  # 6. Analyze the SCADA data using EPyT-Flow -- e.g. plotting data, adding sensor noise, comparing to the simulated data, etc.
	  
	  # Plot pressures at all nodes over time
	  plot_timeseries_data(my_scada_data.get_data_pressures().T,
			       labels=[f"Node {n_id}" for n_id in my_scada_data.sensor_config.pressure_sensors],
			       x_axis_label="Time steps", y_axis_label="Pressure")
	  
	  # ...
```
	
Let me know if this is what you have in mind.

**Comment by meghnathomas** [comment]
Thank you for the fast response, I appreciate how quickly you've addressed all my questions! :-) Yes - I think this is exactly what I was aiming for.  Would you be able to include a working example of this in your docs/examples for users to import their own networks and data? I tried to play with this rough code snippet a little bit and am confused about the format of the pressure data - you mention here that the input should be a numpy array, so I assumed it to be a 1D array containing my time-varying pressure data points, but the API docs say the pressure data input is "Raw pressure values of all nodes as a two-dimensional array – first dimension encodes time, second dimension pressure at nodes." Is that a 2 x T array (where T is the number of time steps) where the first row contains the time steps and second row contains the measurements? In any case,  using the 1D or 2D arrays using this code: 

```
with ScenarioSimulator(f_inp_in='CTown.inp') as sim:
    sim.set_pressure_sensors(sensor_locations=['T1'])	
	  
    my_sensor_config = sim.sensor_config
    scada_data = sim.run_simulation()

    my_measurement_time_points = np.arange(0,3600*24, 3600)
    one_d_pressure_data = np.array([3, 2.82, 2.7, 2.62, 2.7, 2.89, 3.14, 3.26,
                                      3.4, 3.66, 3.73, 3.66, 3.73, 3.88, 4.07, 
                                      4.23, 4.41, 4.44, 4.03, 4.03, 4.03, 4.03,
                                      4.03, 4.03])
    two_d_pressure_data = np.vstack([my_measurement_time_points, one_d_pressure_data])
    
 	  
    my_scada_data = ScadaData(sensor_config=my_sensor_config,
			         frozen_sensor_config=True,	
                                 sensor_readings_time=my_measurement_time_points, 
                                 pressure_data_raw=one_d_pressure_data, 
                                 # pressure_data_raw=two_d_pressure_data,
                                 )
```

throws errors my way so I don't think I'm getting the pressure data format correct!

**Comment by meghnathomas** [comment]
Just to add to my previous comment - the suggestion to add the additional example is totally optional and I think this paper definitely merits publication in JOSS without it, especially as you satisfy your goals to provide WDS data generation capabilities and a platform to host models and benchmark networks and scenarios. I only suggest its addition in the eventuality that researchers want to move beyond testing on benchmark networks/models/scenarios and begin to test their control strategies and analysis approaches on real systems and data.  I have no further comments beyond this and am happy to recommend this paper for acceptance. I will open a separate issue outside of the JOSS review requesting the example at a later date whenever convenient for the authors :-)
